In [1]:
import numpy as np

In [3]:
A = np.array([1, 2, 3, 4])
print(A)

[1 2 3 4]


In [4]:
# ndim : 배열 차원수 표시 
print(np.ndim(A))

1


In [5]:
# 배열의 모양을 표시
print(A.shape)

(4,)


In [6]:
# A.shape 결과 값을 튜플로 반환
print(A.shape[0])

4


In [7]:
B = np.array([[1,2], [3,4], [5,6]])
print(B)

[[1 2]
 [3 4]
 [5 6]]


In [8]:
print(np.ndim(B))

2


In [9]:
print(B.shape)

(3, 2)


In [10]:
print(B.shape[0])
print(B.shape[1])

3
2


In [11]:
A = np.array([[1,2], [3,4]])
print(A.shape)

(2, 2)


In [12]:
B = np.array([[5,6], [7,8]])
print(B.shape)

(2, 2)


In [14]:
print(np.dot(A, B))

[[19 22]
 [43 50]]


In [20]:
def matrixMultiply(m1, m2):
    prodM = []
    for i in range(len(m1)):
        row = m1[i]
        newRow = []
        for j in range(len(m2[0])):
            y = 0
            for x in range(len(row)):
                rowEl = row[x]
                colEl = m2[x][j]
                y += rowEl * colEl
            newRow.append(y)
        prodM.append(newRow)
    return prodM

print(matrixMultiply(A, B))

[[19, 22], [43, 50]]


In [21]:
A = np.array([[1,2,3],[4,5,6]])
print('A.shape : ', A.shape)
B = np.array([[1,2],[3,4],[5,6]])
print('B.shape : ', B.shape)

A.shape :  (2, 3)
B.shape :  (3, 2)


In [22]:
print(np.dot(A, B))

[[22 28]
 [49 64]]


In [23]:
C = np.array([[1,2],[3,4]])
print('A.shape : ', A.shape)
print('C.shape : ', C.shape)

A.shape :  (2, 3)
C.shape :  (2, 2)


In [24]:
print(np.dot(A, C))

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [25]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([7,8])
print(A.shape)
print(B.shape)

(3, 2)
(2,)


In [26]:
print(np.dot(A, B))

[23 53 83]
