In [2]:
import numpy as np

In [3]:
a = np.array([0.3, 2.9, 4.0])
exp_a = np.exp(a) # 지수함수
print(exp_a)

[  1.34985881  18.17414537  54.59815003]


In [4]:
sum_exp_a = np.sum(exp_a)
print(sum_exp_a)

74.1221542102


In [5]:
y = exp_a / sum_exp_a
print(y)

[ 0.01821127  0.24519181  0.73659691]


In [9]:
def softmax_problem(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [10]:
a = np.array([0.3, 2.9, 4.0])
y = softmax_problem(a)
print('y : ', y)
print('np.sum(y) : ', np.sum(y))

y :  [ 0.01821127  0.24519181  0.73659691]
np.sum(y) :  1.0


In [11]:
a = np.array([1010, 1000, 900])
y = softmax_problem(a)
print('y : ', y)
print('np.sum(y) : ', np.sum(y))

y :  [ nan  nan  nan]
np.sum(y) :  nan


/home/paul/.local/lib/python3.5/site-packages/ipykernel/__main__.py:2: RuntimeWarning: overflow encountered in exp
  from ipykernel import kernelapp as app
/home/paul/.local/lib/python3.5/site-packages/ipykernel/__main__.py:4: RuntimeWarning: invalid value encountered in true_divide


In [6]:
a = np.array([1010, 1000, 990])
print(np.exp(a) / np.sum(np.exp(a)))

[ nan  nan  nan]


/home/paul/.local/lib/python3.5/site-packages/ipykernel/__main__.py:2: RuntimeWarning: overflow encountered in exp
  from ipykernel import kernelapp as app
/home/paul/.local/lib/python3.5/site-packages/ipykernel/__main__.py:2: RuntimeWarning: invalid value encountered in true_divide
  from ipykernel import kernelapp as app


In [7]:
c = np.max(a)
print(a - c)

[  0 -10 -20]


In [8]:
print(np.exp(a-c) / np.sum(np.exp(a-c)))

[  9.99954600e-01   4.53978686e-05   2.06106005e-09]


In [12]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [13]:
a = np.array([0.3, 2.9, 4.0])
y = softmax(a)
print('y : ', y)
print('np.sum(y) : ', np.sum(y))

y :  [ 0.01821127  0.24519181  0.73659691]
np.sum(y) :  1.0


In [14]:
a = np.array([1010, 1000, 900])
y = softmax(a)
print('y : ', y)
print('np.sum(y) : ', np.sum(y))

y :  [  9.99954602e-01   4.53978687e-05   1.68883521e-48]
np.sum(y) :  1.0
